### ISSUE TITLE
EventRegistration should include methods from superclasses

### ISSUE THREAD

**Issue by flavor8** [ekuefler/gwt-supereventbus#9]
Right now EventRegistration#getMethods only observes subscribed methods in the same class. It would be nice if it walked up the superclass hierarchy and added any annotated methods from ancestor classes as well.

Use case: I have several views that all share the same layout. I want to encapsulate the behavior of the layout (which has some events it should react to) in a superclass, and have the view classes entirely focused.

**Comment by ekuefler** [comment]
I fixed it to scan all inheritable methods back in commit 0024e3d1a3ac277af000ef5810110028be1f9114 a couple months ago, but haven't pushed out a new version since then. Can you check whether the latest snapshot works like you want it to? If show I can push out a new version to Maven with that commit.

**Comment by flavor8** [comment]
This works great. Please push when you get a chance.

**Comment by ekuefler** [comment]
I've just pushed v0.1.1 with this change. It should be synced to Maven central in a few hours.
